name: Sync Notion blog to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 mins

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install @notionhq/client
          npm install notion-to-md

      - name: Fetch Notion page
        run: |
          cd .github/workflows
          node save_notion_page_as_readme.js
          mv README.md ../../README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: niebayes
          author_email: niebayes@email.com
          message: 'update resume'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
